import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { canonicalJson, hmacSha256, sha256 } from "../lib/commerce/security";
import { generateEmailOtp, mapCeidgResponse, mapCompaniesHouseResponse, mapKrsResponse, mapPolishVatResponse, mapViesResponse, normalizeEuVatNumber, normalizeKrs, normalizeNip, verificationAllowsPayment } from "../lib/server/company-verification";

const krs = (overrides: Record<string, unknown> = {}) => ({ odpis: { naglowekA: { numerKRS: "0000687703", stanPozycji: 1 }, dane: { dzial1: { danePodmiotu: { nazwa: "7SOFTWARE SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ", formaPrawna: "SPÓŁKA Z O.O.", identyfikatory: { nip: "5272813760" } }, siedzibaIAdres: { adres: { ulica: "Jana Pawła II", nrDomu: "27", kodPocztowy: "00-867", miejscowosc: "Warszawa" } } }, dzial2: { reprezentacja: { sposobReprezentacji: "Każdy członek zarządu samodzielnie", sklad: [{ imiona: { imie: "Jan" }, nazwisko: { nazwiskoICzlon: "Kowalski" } }] } }, dzial6: {}, ...overrides } } });
const source = Promise.all([
  readFile(new URL("../lib/server/company-verification.ts", import.meta.url), "utf8"),
  readFile(new URL("../lib/server/orders.ts", import.meta.url), "utf8"),
  readFile(new URL("../lib/server/acceptance.ts", import.meta.url), "utf8"),
  readFile(new URL("../drizzle/0007_company_verification.sql", import.meta.url), "utf8"),
  readFile(new URL("../lib/server/documents.ts", import.meta.url), "utf8"),
]);

test("01 correct 10-digit KRS is accepted", () => assert.equal(normalizeKrs("0000687703"), "0000687703"));
test("02 KRS preserves leading zeroes", () => assert.equal(normalizeKrs("0000000001"), "0000000001"));
test("03 malformed KRS is rejected", () => { assert.throws(() => normalizeKrs("687703"), /10 digits/); assert.throws(() => normalizeKrs("00006877A3"), /10 digits/); });
test("04 a missing register entry enters manual review instead of pretending the company does not exist", async () => { const [verification] = await source; assert.match(verification, /RegistryNotFoundError/); assert.match(verification, /REGISTRY_ENTRY_NOT_FOUND/); assert.match(verification, /MANUAL_REVIEW_REQUIRED/); });
test("05 an active KRS entity maps to an active company snapshot", () => { const result = mapKrsResponse(krs()); assert.equal(result.status, "ACTIVE"); assert.equal(result.legalName.startsWith("7SOFTWARE"), true); });
test("06 liquidation is a risk flag and cannot auto-verify", () => { const result = mapKrsResponse(krs({ dzial6: { likwidacja: { dataOtwarciaLikwidacji: "2026-01-01" } } })); assert.ok(result.riskFlags.includes("IN_LIQUIDATION")); });
test("07 an inactive registry position is detected", () => { const raw = krs(); raw.odpis.naglowekA.stanPozycji = 2; assert.ok(mapKrsResponse(raw).riskFlags.includes("REGISTRY_POSITION_INACTIVE")); });
test("08 KRS service failures become REGISTRY_UNAVAILABLE", async () => { const [verification] = await source; assert.match(verification, /RegistryUnavailableError/); assert.match(verification, /REGISTRY_UNAVAILABLE/); });
test("09 register requests have controlled timeout and retries", async () => { const [verification] = await source; assert.match(verification, /8_000/); assert.match(verification, /attempt < 2/); assert.match(verification, /REGISTRY_TIMEOUT/); });
test("10 registry cache is keyed by adapter, country and identifier and expires", async () => { const [verification] = await source; assert.match(verification, /cacheKey = `\$\{adapter\}:\$\{input\.country\}:\$\{identifier\}`/); assert.match(verification, /24 \* 60 \* 60_000/); });
test("11 customer and registry data mismatch invalidates automatic verification", async () => { const [verification] = await source; assert.match(verification, /CLIENT_REGISTRY_DATA_MISMATCH/); assert.match(verification, /client\.legalName/); });
test("12 CEIDG validates NIP and maps an active sole trader", () => { assert.equal(normalizeNip("527-281-37-60"), "5272813760"); const result = mapCeidgResponse({ firmy: [{ nazwa: "Jan Kowalski Timzy", nip: "5272813760", status: "AKTYWNY", wlasciciel: { imie: "Jan", nazwisko: "Kowalski" }, adresDzialalnosci: { ulica: "Testowa", budynek: "1", kod: "00-001", miasto: "Warszawa" } }] }, "5272813760"); assert.equal(result.riskFlags.length, 0); assert.deepEqual(result.representatives, ["Jan Kowalski"]); });
test("13 foreign Companies House adapter maps company and active directors", () => { const result = mapCompaniesHouseResponse({ company_name: "TIMZY LTD", company_number: "12878269", company_status: "active", type: "ltd", registered_office_address: { premises: "7", address_line_1: "Bell Yard", locality: "London", postal_code: "WC2A 2JR" } }, { items: [{ name: "JANE TEST", officer_role: "director" }] }); assert.equal(result.country, "GB"); assert.deepEqual(result.representatives, ["JANE TEST"]); });
test("14 OTP is a six-digit cryptographically generated value", () => { const values = new Set(Array.from({ length: 100 }, generateEmailOtp)); assert.ok(values.size > 95); for (const value of values) assert.match(value, /^\d{6}$/); });
test("15 a wrong OTP cannot match the stored HMAC", async () => { const id = "challenge"; const good = await hmacSha256(`${id}.123456`, "secret"); const wrong = await hmacSha256(`${id}.654321`, "secret"); assert.notEqual(good, wrong); });
test("16 OTP expiration is enforced at no more than ten minutes", async () => { const [verification] = await source; assert.match(verification, /10 \* 60_000/); assert.match(verification, /Verification code expired/); });
test("17 OTP attempts are capped and the challenge is invalidated", async () => { const [verification] = await source; assert.match(verification, /max_attempts/); assert.match(verification, /attempt_count\+1>=max_attempts/); });
test("18 repeated OTP sends are rate-limited by order, email and IP", async () => { const [verification] = await source; assert.match(verification, /COUNT\(\*\).*email_verification_challenges/); assert.match(verification, />= 3/); });
test("19 single-person representation can be matched", () => { const result = mapKrsResponse(krs()); assert.equal(result.jointRepresentation, false); assert.equal(result.representativeNamesComplete, true); });
test("20 joint representation requires the second-signer path", () => { const raw = krs(); raw.odpis.dane.dzial2.reprezentacja.sposobReprezentacji = "Dwóch członków zarządu działających łącznie"; raw.odpis.dane.dzial2.reprezentacja.sklad.push({ imiona: { imie: "Anna" }, nazwisko: { nazwiskoICzlon: "Nowak" } }); assert.equal(mapKrsResponse(raw).jointRepresentation, true); });
test("21 second signer gets an individual hashed invitation and separate OTP", async () => { const [verification] = await source; assert.match(verification, /second_signer_invites/); assert.match(verification, /tokenHash = await sha256\(token\)/); assert.match(verification, /signer_id,email_hash,code_hash/); });
test("22 signing under power of attorney requires encrypted upload and admin review", async () => { const [verification] = await source; assert.match(verification, /encryptBytes\(bytes/); assert.match(verification, /POWER_OF_ATTORNEY_PENDING_REVIEW/); });
test("23 payment is allowed only for VERIFIED", () => { for (const status of ["NOT_STARTED","REPRESENTATION_CHECK_REQUIRED","SECOND_SIGNER_REQUIRED","POWER_OF_ATTORNEY_REQUIRED","MANUAL_REVIEW_REQUIRED","REJECTED","REGISTRY_UNAVAILABLE"]) assert.equal(verificationAllowsPayment(status), false); assert.equal(verificationAllowsPayment("VERIFIED"), true); });
test("24 changing accepted order data invalidates acceptance and second signer", async () => { const [, orders] = await source; assert.match(orders, /ORDER_CHANGED/); assert.match(orders, /NEEDS_REINVITATION/); assert.match(orders, /SECOND_SIGNER_REQUIRED/); });
test("25 registry snapshot, source, retrieval date and hash are persisted", async () => { const [verification,,, migration] = await source; assert.match(verification, /raw_snapshot_hash/); assert.match(migration, /source_retrieved_at/); assert.match(migration, /mapped_snapshot_json/); });
test("26 certificate is a final PDF page with required acceptance method and signer list", async () => { const [,, acceptance,, documents] = await source; assert.match(documents, /Certyfikat zawarcia umowy elektronicznej/); assert.match(acceptance, /Clickwrap \+ one-time code/); assert.match(documents, /"\\f"/); assert.match(documents, /acceptanceCertificate\.signers/); });
test("27 canonical document evidence hash changes with any accepted content", async () => { const first = await sha256(canonicalJson({ documents: ["a"], price: 12900 })); const second = await sha256(canonicalJson({ documents: ["b"], price: 12900 })); assert.notEqual(first, second); });
test("28 standard process schema has no identity document, PESEL, passport or selfie field", async () => { const [,,, migration] = await source; assert.doesNotMatch(migration, /pesel|passport|selfie|identity_document/i); });
test("29 plaintext OTP is never persisted or passed to logging", async () => { const [verification] = await source; assert.doesNotMatch(verification, /console\.(log|info|warn).*code/i); assert.match(verification, /codeHash/); assert.doesNotMatch(verification, /INSERT INTO email_verification_challenges[^\n]*\bcode\b(?!_hash)/); });
test("30 second-signer links cannot be reused after acceptance", async () => { const [verification,,, migration] = await source; assert.match(verification, /row\.used_at/); assert.match(verification, /SET used_at=\?/); assert.match(migration, /token_hash.*NOT NULL/); });
test("31 EU VAT identifiers are normalized without the country prefix", () => { assert.equal(normalizeEuVatNumber("ES", "ES B-12345678"), "B12345678"); assert.equal(normalizeEuVatNumber("GR", "EL123456789"), "123456789"); });
test("32 a valid VIES response maps official company data", () => { const result = mapViesResponse({ valid: true, vatNumber: "B12345678", name: "TIMZY ESPAÑA SL", address: "CALLE TEST 1\n28001 MADRID", traderStreet: "CALLE TEST 1", traderPostalCode: "28001", traderCity: "MADRID", traderCompanyType: "SL" }, "ES", "B12345678"); assert.equal(result.legalName, "TIMZY ESPAÑA SL"); assert.equal(result.taxNumber, "B12345678"); assert.equal(result.city, "MADRID"); assert.equal(result.verificationSource, "EU_VIES:ES"); });
test("33 a valid but privacy-limited VIES response is flagged for review", () => { const result = mapViesResponse({ isValid: true, vatNumber: "123456789", name: "---", address: "---" }, "GR", "123456789"); assert.ok(result.riskFlags.includes("LIMITED_REGISTRY_DATA")); });
test("34 an invalid VIES number is not presented as a verified company", () => { assert.throws(() => mapViesResponse({ valid: false, vatNumber: "B12345678" }, "ES", "B12345678"), /not active in VIES/); });
test("35 EU countries use the VIES adapter instead of manual declarations", async () => { const [verification] = await source; assert.match(verification, /return "EU_VIES"/); assert.match(verification, /fetchVies\(env, input\.country, identifier, fetcher\)/); });
test("36 the Polish VAT register fills company data when CEIDG credentials are absent", () => { const result = mapPolishVatResponse({ result: { subject: { name: "JAN KOWALSKI TIMZY", nip: "5272813760", regon: "123456789", statusVat: "Czynny", workingAddress: "TESTOWA 1, 00-001 WARSZAWA" } } }, "5272813760"); assert.equal(result.legalName, "JAN KOWALSKI TIMZY"); assert.equal(result.registeredAddress, "TESTOWA 1"); assert.equal(result.postalCode, "00-001"); assert.equal(result.city, "WARSZAWA"); assert.equal(result.verificationSource, "POLISH_VAT_WHITELIST"); });
test("37 CEIDG has an official keyless Polish VAT fallback", async () => { const [verification] = await source; assert.match(verification, /POLISH_VAT_API_BASE_URL/); assert.match(verification, /mapPolishVatResponse\(raw, nip\)/); });
