import assert from "node:assert/strict";
import test from "node:test";
import { createHmac, randomBytes } from "node:crypto";
import { readFile } from "node:fs/promises";
import { canonicalJson, decryptJson, encryptJson, passwordHash, randomToken, sha256, timingSafeEqual, toBase64Url, totpCode, verifyPassword, verifyTotp } from "../lib/commerce/security";
import { generateContractPdf, renderContractHtml, type ContractBundle } from "../lib/server/documents";
import { verifyStripeEvent } from "../lib/server/stripe";
import { stripeEventReplayDecision, stripePaymentTotals } from "../lib/server/webhooks";
import { adminMfaRequired } from "../lib/server/admin-auth";

test("encrypted customer data round-trips and does not expose plaintext", async () => { const key = toBase64Url(randomBytes(32)); const value = { company: "Sensitive Company", taxId: "PL123" }; const encrypted = await encryptJson(value, key); assert.doesNotMatch(encrypted, /Sensitive|PL123/); assert.deepEqual(await decryptJson(encrypted, key), value); });
test("password hashing uses salt and verifies without storing plaintext", async () => { const salt = toBase64Url(randomBytes(16)); const hash = await passwordHash("correct horse battery staple", salt, 10_000); assert.equal(await verifyPassword("correct horse battery staple", salt, 10_000, hash), true); assert.equal(await verifyPassword("wrong", salt, 10_000, hash), false); });
test("TOTP accepts current window and rejects arbitrary code", async () => { const timestamp = 1_700_000_000_000; const secret = "JBSWY3DPEHPK3PXP"; const code = await totpCode(secret, timestamp); assert.match(code, /^\d{6}$/); assert.equal(await verifyTotp(secret, code, timestamp), true); assert.equal(await verifyTotp(secret, "000000", timestamp), false); });
test("MFA can be disabled locally but is always forced in production", () => { assert.equal(adminMfaRequired({ APP_ENV: "local", ADMIN_MFA_REQUIRED: "false" }), false); assert.equal(adminMfaRequired({ APP_ENV: "development" }), true); assert.equal(adminMfaRequired({ APP_ENV: "production", ADMIN_MFA_REQUIRED: "false" }), true); });
test("canonical JSON and hashes are stable across object key order", async () => { assert.equal(canonicalJson({ b: 2, a: 1 }), canonicalJson({ a: 1, b: 2 })); assert.equal(await sha256(canonicalJson({ b: 2, a: 1 })), await sha256(canonicalJson({ a: 1, b: 2 }))); });
test("constant-time comparison rejects different lengths and content", () => { assert.equal(timingSafeEqual("same", "same"), true); assert.equal(timingSafeEqual("same", "diff"), false); assert.equal(timingSafeEqual("a", "aa"), false); });
test("random session tokens have sufficient entropy and uniqueness", () => { const tokens = new Set(Array.from({ length: 100 }, () => randomToken())); assert.equal(tokens.size, 100); for (const token of tokens) assert.ok(token.length >= 40); });
test("Stripe webhook signature uses raw body, timestamp tolerance and endpoint secret", async () => { const body = JSON.stringify({ id: "evt_test", type: "checkout.session.completed", created: 1, data: { object: { id: "cs_test" } } }); const timestamp = Math.floor(Date.now() / 1000); const secret = "whsec_test_secret"; const signature = createHmac("sha256", secret).update(`${timestamp}.${body}`).digest("hex"); const event = await verifyStripeEvent(body, `t=${timestamp},v1=${signature}`, secret); assert.equal(event.id, "evt_test"); await assert.rejects(() => verifyStripeEvent(`${body} `, `t=${timestamp},v1=${signature}`, secret), /Invalid Stripe signature/); });
test("stale Stripe webhook signatures are rejected", async () => { const body = JSON.stringify({ id: "evt_old", type: "invoice.paid", data: { object: { id: "in_old" } } }); const timestamp = 1; const secret = "whsec_test"; const signature = createHmac("sha256", secret).update(`${timestamp}.${body}`).digest("hex"); await assert.rejects(() => verifyStripeEvent(body, `t=${timestamp},v1=${signature}`, secret), /Stale/); });
test("processed Stripe webhook is ignored but a failed event is retryable", () => { assert.equal(stripeEventReplayDecision({ processingStatus: "PROCESSED", payloadHash: "same" }, "same"), "DUPLICATE"); assert.equal(stripeEventReplayDecision({ processingStatus: "FAILED", payloadHash: "same" }, "same"), "RETRY"); assert.throws(() => stripeEventReplayDecision({ processingStatus: "FAILED", payloadHash: "different" }, "same"), /different payload/); });
test("actual Stripe tax and gross total are captured only from webhook data", () => { assert.deepEqual(stripePaymentTotals({ total_details: { amount_tax: 2300 }, amount_total: 12_300 }), { taxMinor: 2300, totalMinor: 12_300 }); assert.deepEqual(stripePaymentTotals({ total_taxes: [{ amount: 100 }, { amount: 200 }], total: 10_300 }), { taxMinor: 300, totalMinor: 10_300 }); assert.deepEqual(stripePaymentTotals({}), { taxMinor: null, totalMinor: null }); });

const bundle: ContractBundle = {
  schemaVersion: 1, orderId: "order-test", orderNumber: "TZ-TEST", generatedAt: "2026-08-17T12:00:00.000Z", language: "pl", quoteFingerprint: "hash",
  seller: { code: "INNOVARE", legalName: "INNOVARE GROUP LTD", companyNumber: "12878269", addressLine1: "7 Bell Yard", postalCode: "WC2A 2JR", city: "London", countryCode: "GB" },
  technologyProvider: { code: "INNOVARE", legalName: "INNOVARE GROUP LTD", companyNumber: "12878269", addressLine1: "7 Bell Yard", postalCode: "WC2A 2JR", city: "London", countryCode: "GB" },
  client: { legalName: "Żółć Studio sp. z o.o.", legalForm: "sp. z o.o.", registrationCountry: "PL", registeredAddress: "ul. Łąkowa 1", postalCode: "00-001", city: "Warszawa", billingAddressDifferent: false, billingCountry: "PL", taxId: "PL123", companyNumber: "0000123456", entityType: "PL_KRS", registryName: "Krajowy Rejestr Sądowy", representativeName: "Łukasz Żak", representativePosition: "Prezes", representativeAuthorityBasis: "Samodzielna reprezentacja zgodnie z KRS", businessEmail: "legal@example.com", phone: "+48123456789", brandName: "Żółć", appName: "Żółć App", communicationLanguage: "pl", authorityConfirmed: true, companyDataConfirmed: true },
  commercialSummary: { market: "INTERNATIONAL", currency: "EUR", contractTerm: "ANNUAL_12", lines: [{ itemType: "PLAN", catalogItemId: "plan", priceVersionId: "price", name: "Pakiet Łąka", paymentType: "MONTHLY", quantity: 1, unitAmountMinor: 10000, totalAmountMinor: 10000, stripePriceId: "price_test", included: false }], monthlyNetMinor: 10000, oneTimeNetMinor: 0, activationFeeMinor: 0, annualCommitmentNetMinor: 120000, deploymentDays: 7 },
  documents: [{ kind: "AGREEMENT", versionId: "v1", version: 1, contentHash: "doc", title: "Umowa", sections: ["Zażółć gęślą jaźń."] }, { kind: "TERMS", versionId: "v2", version: 1, contentHash: "doc2", title: "Regulamin", sections: ["Warunki testowe."] }, { kind: "DPA", versionId: "v3", version: 1, contentHash: "doc3", title: "DPA", sections: ["Powierzenie danych."] }, { kind: "PRIVACY", versionId: "v4", version: 1, contentHash: "doc4", title: "Prywatność", sections: ["Minimalizacja danych."] }],
  mandatoryTerms: ["Około 7 dni roboczych, bez gwarancji terminu."],
};

test("contract HTML contains the immutable commercial and document snapshot", () => { const html = renderContractHtml(bundle); assert.match(html, /TZ-TEST/); assert.match(html, /Żółć Studio/); assert.match(html, /Pakiet Łąka/); assert.match(html, /Umowa · v1/); });
test("PDF generation embeds the supplied Unicode font and creates a real PDF", async () => { const font = await readFile(new URL("../public/assets/fonts/manrope-latin-ext.woff2", import.meta.url)); const assets = { fetch: async () => new Response(font) } as unknown as Fetcher; const pdf = await generateContractPdf(bundle, assets); assert.equal(new TextDecoder().decode(pdf.slice(0, 5)), "%PDF-"); assert.ok(pdf.byteLength > 2_000); });
