"use client";

import { useCallback, useEffect, useState } from "react";
import { AdminLanguageSwitch, useAdminI18n } from "./AdminI18n";
import { adminStatusLabel } from "./AdminI18nUtils";

type Detail = { order: Record<string, unknown>; items: Record<string, unknown>[]; acceptances: Record<string, unknown>[]; documents: Record<string, unknown>[]; deployments: Record<string, unknown>[]; notifications: Record<string, unknown>[]; provisioning: Record<string, unknown> | null; audit: Record<string, unknown>[] };

export function AdminOrderDetail({ orderId }: { orderId: string }) {
  const { locale, setLocale, t } = useAdminI18n();
  const [csrf, setCsrf] = useState(""); const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/admin/orders/${orderId}`, { credentials: "same-origin" }); if (response.status === 401) { window.location.assign(`/admin/login/?return=/admin/orders/${orderId}/`); return; } const payload = await response.json() as { ok: boolean; message?: string; detail: Detail }; if (!response.ok || !payload.ok) throw new Error(payload.message || t("orderUnavailable")); setDetail(payload.detail); }, [orderId, t]);
  useEffect(() => { void fetch("/api/admin/session", { credentials: "same-origin" }).then((response) => response.json() as Promise<{ ok: boolean; csrfToken: string }>).then((payload) => { if (!payload.ok) throw new Error(); setCsrf(payload.csrfToken); return load(); }).catch(() => window.location.assign("/admin/login/")); }, [load]);
  async function action(path: string, body: unknown = {}) { setError(""); try { const response = await fetch(path, { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", "x-csrf-token": csrf }, body: JSON.stringify(body) }); const payload = await response.json() as { ok: boolean; message?: string }; if (!response.ok || !payload.ok) throw new Error(payload.message || t("actionFailed")); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : t("actionFailed")); } }
  if (!detail) return <main className="admin-loading">{t("loadingOrder")}</main>;
  const deploymentStatuses = ["AWAITING_PAYMENT","AWAITING_CLIENT_DATA","CLIENT_DATA_COMPLETE","IMPLEMENTATION_STARTED","CONFIGURATION","TESTING","AWAITING_CLIENT_APPROVAL","SUBMITTED_GOOGLE_PLAY","SUBMITTED_APPLE_APP_STORE","AWAITING_STORE_DECISION","PUBLISHED","IMPLEMENTATION_COMPLETED","IMPLEMENTATION_PAUSED"];
  return <main className="admin-detail"><header><a href="/admin/">← {t("administration")}</a><AdminLanguageSwitch locale={locale} setLocale={setLocale} /><span>{String(detail.order.order_number)}</span></header><section><p className="eyebrow">{t("orderEvidence")}</p><h1>{String(detail.order.order_number)}</h1><div className="admin-detail-actions"><button className="button" onClick={() => void action(`/api/admin/orders/${orderId}/retry-provisioning`)}>{t("retryProvisioning")}</button><button className="button button--light" onClick={() => void action(`/api/admin/orders/${orderId}/resend-notifications`)}>{t("resendNotifications")}</button></div>{error ? <div className="contract-error">{error}</div> : null}<form className="admin-form admin-form--wide" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void action(`/api/admin/orders/${orderId}/deployment-status`, { status: data.get("status"), expectedStartDate: data.get("expectedStartDate"), expectedReadyDate: data.get("expectedReadyDate"), googlePlayStatus: data.get("googlePlayStatus"), appleAppStoreStatus: data.get("appleAppStoreStatus"), note: data.get("note") }); }}><h2>{t("addDeploymentStatus")}</h2><div className="admin-form-row"><select name="status">{deploymentStatuses.map((status) => <option key={status} value={status}>{adminStatusLabel(status, locale)}</option>)}</select><input name="expectedStartDate" type="date" aria-label={t("expectedStart")} title={t("expectedStart")} /><input name="expectedReadyDate" type="date" aria-label={t("expectedReady")} title={t("expectedReady")} /></div><div className="admin-form-row"><input name="googlePlayStatus" placeholder={t("googleStatus")} /><input name="appleAppStoreStatus" placeholder={t("appleStatus")} /></div><textarea name="note" placeholder={t("internalNote")} /><button className="button">{t("recordStatus")}</button></form><DetailBlock title={t("order")} value={detail.order} open /><DetailBlock title={t("immutableItems")} value={detail.items} /><DetailBlock title={t("clickwrapAcceptance")} value={detail.acceptances} /><div className="admin-table-wrap"><h2>{t("navDocuments")}</h2>{detail.documents.map((document) => <a key={String(document.id)} href={`/api/commerce/documents/${String(document.id)}?order=${orderId}`}>{String(document.kind)} · {String(document.plaintext_hash)} · {t("download")}</a>)}</div><DetailBlock title={t("deploymentHistory")} value={detail.deployments} /><DetailBlock title={t("emailHistory")} value={detail.notifications} /><DetailBlock title={t("provisioning")} value={detail.provisioning} /><DetailBlock title={t("auditLog")} value={detail.audit} /></section></main>;
}

function DetailBlock({ title, value, open = false }: { title: string; value: unknown; open?: boolean }) { return <details className="admin-detail-block" open={open}><summary>{title}</summary><pre>{JSON.stringify(value, null, 2)}</pre></details>; }
