"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { trackEvent } from "./Analytics";
import type { ClientLegalData, CommerceCatalog, CommerceQuote, ContractTerm, Locale, MarketCode, OrderSelection } from "../lib/commerce/types";

type ApiResult = { ok: boolean; message?: string; code?: string; [key: string]: unknown };
type OrderView = { id: string; orderNumber: string; status: string; market?: MarketCode; language?: Locale; currency?: string; contractTerm?: ContractTerm; monthlyNetMinor?: number; oneTimeNetMinor?: number; activationFeeMinor?: number; dueTodayMinor?: number; deploymentDays?: number };

const processLabels = {
  pl: ["Rynek", "Język", "Umowa", "Pakiet", "Dodatki", "Firma", "Podsumowanie", "Dokumenty", "Akceptacja", "Płatność", "Potwierdzenie", "Wdrożenie"],
  en: ["Market", "Language", "Agreement", "Plan", "Add-ons", "Company", "Summary", "Documents", "Acceptance", "Payment", "Confirmation", "Onboarding"],
  es: ["Mercado", "Idioma", "Contrato", "Plan", "Extras", "Empresa", "Resumen", "Documentos", "Aceptación", "Pago", "Confirmación", "Implementación"],
};

const copy = {
  pl: {
    title: "Skonfiguruj Timzy i zawrzyj umowę online", intro: "Rynek rozliczeniowy określa sprzedawcę i walutę. Język możesz zmienić niezależnie.", next: "Dalej", back: "Wstecz",
    save: "Zapisz dane i przygotuj podsumowanie", country: "Kraj rejestracji firmy", billingCountry: "Kraj rozliczeniowy", market: "Rynek rozliczeniowy", confirmMarket: "Potwierdzam kraj, rynek, walutę i wskazanego sprzedawcę.",
    language: "Język interfejsu i dokumentów", term: "Rodzaj umowy", annual: "12 miesięcy", annualText: "0 opłaty aktywacyjnej, płatność miesięczna, minimalny okres 12 miesięcy.", open: "Bezterminowa", openText: "30 dni wypowiedzenia i oddzielna opłata aktywacyjna.",
    plan: "Wybierz pakiet", addons: "Wybierz usługi dodatkowe", included: "Zawarte w pakiecie", company: "Dane prawne klienta", summary: "Sprawdź ofertę", documents: "Przeczytaj i pobierz dokumenty", acceptance: "Świadoma akceptacja", noOffer: "Oferta nie została jeszcze opublikowana. Administrator musi zatwierdzić ceny i dokumenty.",
    seller: "Sprzedawca", provider: "Dostawca Technologii", currency: "Waluta", monthly: "Miesięcznie netto", oneTime: "Jednorazowo netto", activation: "Opłata aktywacyjna", today: "Płatne dziś netto", tax: "Podatek", taxPending: "Ostatecznie obliczy Stripe na backendzie", annualValue: "Orientacyjna wartość zobowiązania za 12 miesięcy", recurringNote: "Płatności są pobierane miesięcznie, a nie jednorazowo za cały rok.", implementation: "Przewidywane wdrożenie", businessDays: "dni roboczych", nextCharge: "Następne obciążenie", nextChargeStripe: "Datę potwierdzi Stripe po płatności", startDate: "Rozpoczęcie", startAfterPayment: "Po potwierdzeniu płatności i kompletu danych",
    rollout: "Standardowe przygotowanie podstawowej wersji trwa około 7 dni roboczych po płatności i otrzymaniu kompletu prawidłowych danych, materiałów oraz akceptacji. Termin nie jest gwarantowany i może zależeć od zakresu oraz weryfikacji Google Play i Apple App Store.",
    preview: "Czytaj dokumenty", pdf: "Pobierz PDF", accept1: "Przeczytałem i akceptuję Umowę oraz Regulamin", accept2: "Akceptuję warunki przetwarzania danych i umowę powierzenia", accept3: "Potwierdzam, że jestem uprawniony do zawarcia Umowy w imieniu wskazanej firmy", accept4: "Potwierdzam minimalny 12-miesięczny okres obowiązywania Umowy i obowiązek miesięcznych płatności", accept5: "Wyrażam zgodę na cykliczne obciążanie wybranej metody płatności zgodnie z Umową", final: "Zawieram umowę i przechodzę do płatności", recommended: "Polecany", perMonth: "miesiąc", quantity: "Liczba", billingDifferent: "Adres rozliczeniowy jest inny", documentNames: ["Umowa", "Regulamin", "Umowa powierzenia danych", "Polityka prywatności"],
    fields: { legalName: "Pełna nazwa firmy", legalForm: "Forma prawna", registeredAddress: "Adres rejestrowy", postalCode: "Kod pocztowy", city: "Miasto", taxId: "NIP / VAT ID", companyNumber: "Numer rejestrowy firmy", representativeName: "Imię i nazwisko reprezentanta", representativePosition: "Stanowisko / podstawa umocowania", businessEmail: "E-mail firmowy", phone: "Telefon", brandName: "Nazwa marki", domain: "Domena", appName: "Planowana nazwa aplikacji", billingAddress: "Adres rozliczeniowy", billingPostalCode: "Kod pocztowy rozliczeniowy", billingCity: "Miasto rozliczeniowe" },
  },
  en: {
    title: "Configure Timzy and enter into the agreement online", intro: "The billing market determines the seller and currency. You can change the language independently.", next: "Continue", back: "Back", save: "Save company data and prepare summary",
    country: "Company registration country", billingCountry: "Billing country", market: "Billing market", confirmMarket: "I confirm the country, market, currency and stated seller.", language: "Interface and document language", term: "Agreement type", annual: "12 months", annualText: "No activation fee, monthly billing and a 12-month minimum term.", open: "Open-ended", openText: "30 days' notice and a separate activation fee.",
    plan: "Choose a plan", addons: "Choose add-ons", included: "Included in the plan", company: "Client legal data", summary: "Review the offer", documents: "Read and save the documents", acceptance: "Informed acceptance", noOffer: "The offer has not been published yet. An administrator must approve prices and legal documents.",
    seller: "Seller", provider: "Technology Provider", currency: "Currency", monthly: "Monthly net", oneTime: "One-time net", activation: "Activation fee", today: "Due today net", tax: "Tax", taxPending: "Calculated finally by Stripe on the backend", annualValue: "Indicative 12-month commitment value", recurringNote: "Payments are collected monthly, not as a single annual payment.", implementation: "Estimated implementation", businessDays: "business days", nextCharge: "Next charge", nextChargeStripe: "Stripe confirms the date after payment", startDate: "Start", startAfterPayment: "After payment and complete data are confirmed",
    rollout: "Standard preparation of the basic version takes approximately 7 business days after payment and receipt of complete, correct data, materials and approvals. This is not a guaranteed deadline and can depend on scope and Google Play or Apple App Store review.",
    preview: "Read documents", pdf: "Download PDF", accept1: "I have read and accept the Agreement and Terms", accept2: "I accept the data processing terms and DPA", accept3: "I confirm I am authorised to enter into the Agreement for the stated company", accept4: "I confirm the 12-month minimum term and the obligation to make monthly payments", accept5: "I consent to recurring charges to the selected payment method under the Agreement", final: "Enter into the agreement and proceed to payment", recommended: "Recommended", perMonth: "month", quantity: "Quantity", billingDifferent: "Billing address is different", documentNames: ["Agreement", "Terms", "Data Processing Agreement", "Privacy policy"],
    fields: { legalName: "Legal company name", legalForm: "Legal form", registeredAddress: "Registered address", postalCode: "Postal code", city: "City", taxId: "Tax ID / VAT ID", companyNumber: "Company registration number", representativeName: "Representative name", representativePosition: "Position / authority", businessEmail: "Business email", phone: "Phone", brandName: "Brand name", domain: "Domain", appName: "Planned app name", billingAddress: "Billing address", billingPostalCode: "Billing postal code", billingCity: "Billing city" },
  },
  es: {
    title: "Configura Timzy y celebra el contrato online", intro: "El mercado de facturación determina el vendedor y la moneda. El idioma se puede cambiar de forma independiente.", next: "Continuar", back: "Atrás", save: "Guardar datos y preparar el resumen",
    country: "País de registro", billingCountry: "País de facturación", market: "Mercado de facturación", confirmMarket: "Confirmo el país, el mercado, la moneda y el vendedor indicado.", language: "Idioma de la interfaz y los documentos", term: "Tipo de contrato", annual: "12 meses", annualText: "Sin cuota de activación, pago mensual y plazo mínimo de 12 meses.", open: "Indefinido", openText: "30 días de preaviso y una cuota de activación separada.",
    plan: "Elige un plan", addons: "Elige extras", included: "Incluido en el plan", company: "Datos legales del cliente", summary: "Revisa la oferta", documents: "Lee y guarda los documentos", acceptance: "Aceptación informada", noOffer: "La oferta todavía no está publicada. Un administrador debe aprobar los precios y los documentos legales.",
    seller: "Vendedor", provider: "Proveedor de Tecnología", currency: "Moneda", monthly: "Mensual neto", oneTime: "Único neto", activation: "Cuota de activación", today: "A pagar hoy neto", tax: "Impuestos", taxPending: "Cálculo final por Stripe en el backend", annualValue: "Valor orientativo del compromiso de 12 meses", recurringNote: "Los pagos se cobran mensualmente, no en un único pago anual.", implementation: "Implementación estimada", businessDays: "días laborables", nextCharge: "Siguiente cargo", nextChargeStripe: "Stripe confirma la fecha después del pago", startDate: "Inicio", startAfterPayment: "Tras confirmar el pago y los datos completos",
    rollout: "La preparación estándar de la versión básica tarda aproximadamente 7 días laborables desde el pago y la recepción de todos los datos, materiales y aprobaciones correctos. No es un plazo garantizado y puede depender del alcance y de la revisión de Google Play o Apple App Store.",
    preview: "Leer documentos", pdf: "Descargar PDF", accept1: "He leído y acepto el Contrato y las Condiciones", accept2: "Acepto las condiciones de tratamiento de datos y el DPA", accept3: "Confirmo que estoy autorizado para celebrar el Contrato en nombre de la empresa indicada", accept4: "Confirmo el plazo mínimo de 12 meses y la obligación de pagos mensuales", accept5: "Acepto los cargos recurrentes en el método de pago seleccionado conforme al Contrato", final: "Celebrar el contrato y continuar al pago", recommended: "Recomendado", perMonth: "mes", quantity: "Cantidad", billingDifferent: "La dirección de facturación es diferente", documentNames: ["Contrato", "Condiciones", "Acuerdo de tratamiento de datos", "Política de privacidad"],
    fields: { legalName: "Razón social", legalForm: "Forma jurídica", registeredAddress: "Domicilio social", postalCode: "Código postal", city: "Ciudad", taxId: "NIF / VAT ID", companyNumber: "Número de registro mercantil", representativeName: "Nombre del representante", representativePosition: "Cargo / facultad", businessEmail: "Correo de empresa", phone: "Teléfono", brandName: "Nombre de la marca", domain: "Dominio", appName: "Nombre previsto de la aplicación", billingAddress: "Dirección de facturación", billingPostalCode: "Código postal de facturación", billingCity: "Ciudad de facturación" },
  },
};

const emptyClient: ClientLegalData = { legalName: "", legalForm: "", registrationCountry: "PL", registeredAddress: "", postalCode: "", city: "", billingAddressDifferent: false, billingAddress: "", billingPostalCode: "", billingCity: "", billingCountry: "PL", taxId: "", companyNumber: "", representativeName: "", representativePosition: "", businessEmail: "", phone: "", brandName: "", domain: "", appName: "", communicationLanguage: "pl", authorityConfirmed: false };

async function api(path: string, options: RequestInit = {}): Promise<ApiResult> {
  const response = await fetch(path, { credentials: "same-origin", ...options, headers: { "content-type": "application/json", ...(options.headers ?? {}) } });
  const payload = await response.json() as ApiResult; if (!response.ok || !payload.ok) throw new Error(payload.message || payload.code || "Request failed"); return payload;
}

function money(minor: number | null | undefined, currency: string, locale: Locale) { return new Intl.NumberFormat(locale, { style: "currency", currency }).format((minor ?? 0) / 100); }

function Field({ label, name, value, onChange, type = "text", required = true, autoComplete }: { label: string; name: keyof ClientLegalData; value: string; onChange: (name: keyof ClientLegalData, value: string) => void; type?: string; required?: boolean; autoComplete?: string }) {
  return <label className="contract-field"><span>{label}{required ? " *" : ""}</span><input name={String(name)} type={type} value={value} required={required} autoComplete={autoComplete} onChange={(event) => onChange(name, event.target.value)} /></label>;
}

function Summary({ quote, catalog, locale, selection }: { quote: CommerceQuote | null; catalog: CommerceCatalog | null; locale: Locale; selection: OrderSelection }) {
  const t = copy[locale]; const currency = quote?.currency ?? catalog?.market.currency ?? (catalog?.market.code === "PL" ? "PLN" : "EUR");
  return <div className="contract-summary-card"><p className="eyebrow">{t.summary}</p><h2>{quote ? money(quote.dueTodayNetMinor, currency, locale) : "—"}</h2><dl><div><dt>{t.country}</dt><dd>{selection.registrationCountry}</dd></div><div><dt>{t.billingCountry}</dt><dd>{selection.billingCountry}</dd></div><div><dt>{t.market}</dt><dd>{selection.market}</dd></div><div><dt>{t.seller}</dt><dd>{catalog?.market.seller.legalName ?? "—"}</dd></div><div><dt>{t.provider}</dt><dd>{catalog?.market.technologyProvider.legalName ?? "—"}</dd></div><div><dt>{t.language}</dt><dd>{locale.toUpperCase()}</dd></div><div><dt>{t.currency}</dt><dd>{currency}</dd></div><div><dt>{t.term}</dt><dd>{selection.contractTerm === "ANNUAL_12" ? t.annual : t.open}</dd></div><div><dt>{t.startDate}</dt><dd>{t.startAfterPayment}</dd></div><div><dt>{t.monthly}</dt><dd>{money(quote?.monthlyNetMinor, currency, locale)}</dd></div><div><dt>{t.oneTime}</dt><dd>{money(quote?.oneTimeNetMinor, currency, locale)}</dd></div><div><dt>{t.activation}</dt><dd>{money(quote?.activationFeeMinor, currency, locale)}</dd></div><div><dt>{t.tax}</dt><dd>{t.taxPending}</dd></div><div><dt>{t.nextCharge}</dt><dd>{t.nextChargeStripe}</dd></div><div><dt>{t.implementation}</dt><dd>{quote ? `≈ ${quote.deploymentDays} ${t.businessDays}` : "—"}</dd></div></dl>{quote?.contractTerm === "ANNUAL_12" ? <p className="summary-commitment"><b>{t.annualValue}</b><span>{money(quote.annualCommitmentNetMinor, currency, locale)}</span></p> : null}<p className="summary-note">{t.recurringNote}</p></div>;
}

export function ContractFlow({ initialLocale }: { initialLocale: Locale }) {
  const started = useRef(false); const [phase, setPhase] = useState(0); const [csrf, setCsrf] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [order, setOrder] = useState<OrderView | null>(null); const [catalog, setCatalog] = useState<CommerceCatalog | null>(null); const [quote, setQuote] = useState<CommerceQuote | null>(null); const [marketConfirmed, setMarketConfirmed] = useState(false);
  const [selection, setSelection] = useState<OrderSelection>({ market: initialLocale === "pl" ? "PL" : "INTERNATIONAL", language: initialLocale, contractTerm: "ANNUAL_12", registrationCountry: initialLocale === "pl" ? "PL" : initialLocale === "es" ? "ES" : "GB", billingCountry: initialLocale === "pl" ? "PL" : initialLocale === "es" ? "ES" : "GB", planId: null, addons: [] });
  const [client, setClient] = useState<ClientLegalData>({ ...emptyClient, registrationCountry: selection.registrationCountry, billingCountry: selection.billingCountry, communicationLanguage: selection.language });
  const [acceptance, setAcceptance] = useState({ agreementAndTerms: false, dataProcessing: false, authority: false, annualCommitment: false, recurringPayment: false });
  const locale = selection.language; const t = copy[locale];

  const loadCatalog = useCallback(async (scope: OrderSelection) => {
    const result = await api(`/api/commerce/catalog?market=${scope.market}&language=${scope.language}`); setCatalog(result.catalog as CommerceCatalog);
  }, []);

  useEffect(() => {
    void (async () => {
      try {
        const bootstrap = await api("/api/commerce/bootstrap"); setCsrf(bootstrap.csrfToken as string); setOrder(bootstrap.order as OrderView);
        const current = await api("/api/commerce/draft"); const saved = current.selection as Partial<OrderSelection>;
        if (saved.market && saved.language && saved.contractTerm && saved.registrationCountry && saved.billingCountry) {
          const restored = saved as OrderSelection; setSelection(restored); if (current.client) setClient(current.client as ClientLegalData); await loadCatalog(restored);
        } else await loadCatalog(selection);
        if (!started.current) { trackEvent("contract_flow_started"); started.current = true; }
      } catch (failure) { setError(failure instanceof Error ? failure.message : "Could not start the contract flow"); }
    })();
  // Initial bootstrap is intentionally performed once.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => { if (!csrf) return; const timeout = window.setTimeout(() => { void api("/api/commerce/selection", { method: "POST", headers: { "x-csrf-token": csrf }, body: JSON.stringify({ selection }) }).catch(() => undefined); }, 350); return () => window.clearTimeout(timeout); }, [selection, csrf]);
  useEffect(() => {
    const timeout = window.setTimeout(() => { if (!csrf || (!selection.planId && selection.addons.length === 0)) { setQuote(null); return; } void api("/api/commerce/quote", { method: "POST", headers: { "x-csrf-token": csrf }, body: JSON.stringify({ selection }) }).then((result) => setQuote(result.quote as CommerceQuote)).catch(() => setQuote(null)); }, 300);
    return () => window.clearTimeout(timeout);
  }, [selection, csrf]);

  const changeSelection = <K extends keyof OrderSelection>(key: K, value: OrderSelection[K]) => {
    setError(""); setMarketConfirmed(key === "language" ? marketConfirmed : false); setAcceptance({ agreementAndTerms: false, dataProcessing: false, authority: false, annualCommitment: false, recurringPayment: false });
    const nextSelection = { ...selection, [key]: value } as OrderSelection;
    if (key === "planId") {
      const nextPlanId = value as string | null;
      nextSelection.addons = selection.addons.filter((chosen) => { const addon = catalog?.addons.find((item) => item.id === chosen.addonId); return Boolean(addon && (nextPlanId ? addon.compatiblePlanIds.length === 0 || addon.compatiblePlanIds.includes(nextPlanId) : addon.standalone)); });
    }
    setSelection(nextSelection);
    if ((key === "market" || key === "language") && csrf) void loadCatalog(nextSelection).catch((failure) => setError(failure instanceof Error ? failure.message : "Catalogue unavailable"));
    if (key === "market") trackEvent("market_selected", { market: value }); if (key === "language") trackEvent("language_selected", { document_language: value });
    if (key === "contractTerm") trackEvent("contract_term_selected", { contract_term: value }); if (key === "planId") trackEvent("plan_selected", { plan_id: value });
  };
  const setCountry = (key: "registrationCountry" | "billingCountry", value: string) => {
    const country = value.toUpperCase().slice(0, 2); const market: MarketCode = key === "billingCountry" ? (country === "PL" ? "PL" : "INTERNATIONAL") : selection.market;
    setSelection((current) => ({ ...current, [key]: country, ...(key === "billingCountry" ? { market } : {}) })); setClient((current) => ({ ...current, [key]: country })); setMarketConfirmed(false);
  };
  const setClientField = (name: keyof ClientLegalData, value: string | boolean) => setClient((current) => ({ ...current, [name]: value }));
  const selectedPlan = catalog?.plans.find((plan) => plan.id === selection.planId);
  const toggleAddon = (addonId: string, enabled: boolean) => { setSelection((current) => ({ ...current, addons: enabled ? [...current.addons, { addonId, quantity: 1 }] : current.addons.filter((item) => item.addonId !== addonId) })); trackEvent("addon_selected", { addon_id: addonId, selected: enabled }); };
  const setAddonQuantity = (addonId: string, quantity: number) => setSelection((current) => ({ ...current, addons: current.addons.map((item) => item.addonId === addonId ? { ...item, quantity } : item) }));

  const next = () => { setError(""); if (phase === 0 && !marketConfirmed) { setError(t.confirmMarket); return; } if (phase === 3 && !selection.planId && !catalog?.addons.some((addon) => addon.standalone)) { setError(t.plan); return; } if (phase === 4 && !selection.planId && selection.addons.length === 0) { setError(t.addons); return; } setPhase((current) => Math.min(8, current + 1)); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submitCompany = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const result = await api("/api/commerce/draft", { method: "POST", headers: { "x-csrf-token": csrf }, body: JSON.stringify({ selection, client: { ...client, registrationCountry: selection.registrationCountry, billingCountry: selection.billingCountry, communicationLanguage: selection.language } }) }); setOrder(result.order as OrderView); setQuote(result.quote as CommerceQuote); setCatalog(result.catalog as CommerceCatalog); setPhase(6); } catch (failure) { setError(failure instanceof Error ? failure.message : "Could not save company data"); } finally { setBusy(false); } };
  const finish = async () => { setBusy(true); setError(""); try { const accepted = await api("/api/commerce/accept", { method: "POST", headers: { "x-csrf-token": csrf }, body: JSON.stringify({ acceptance }) }); setOrder(accepted.order as OrderView); trackEvent("contract_accepted", { market: selection.market, contract_term: selection.contractTerm }); const checkout = await api("/api/commerce/checkout", { method: "POST", headers: { "x-csrf-token": csrf }, body: "{}" }); trackEvent("checkout_started", { market: selection.market, currency: quote?.currency, contract_term: selection.contractTerm }); window.location.assign(checkout.checkoutUrl as string); } catch (failure) { setError(failure instanceof Error ? failure.message : "Checkout could not be started"); } finally { setBusy(false); } };
  const allAccepted = acceptance.agreementAndTerms && acceptance.dataProcessing && acceptance.authority && acceptance.recurringPayment && (selection.contractTerm !== "ANNUAL_12" || acceptance.annualCommitment);

  return <main className="contract-page" lang={locale}><header className="contract-header"><a href={locale === "pl" ? "/pl/" : locale === "es" ? "/es/" : "/"}><img src="/assets/timzy-logo-official-purple.png" width="307" height="158" alt="Timzy" /></a><span>{order?.orderNumber}</span></header><div className="contract-shell"><nav className="contract-progress" aria-label={locale === "pl" ? "Postęp zawierania umowy" : locale === "es" ? "Progreso de contratación" : "Contract progress"}>{processLabels[locale].map((label, index) => <span key={label} aria-current={index === phase ? "step" : undefined} className={index === phase ? "is-current" : index < phase ? "is-complete" : ""}><i>{index < phase ? "✓" : index + 1}</i>{label}</span>)}</nav><div className="contract-workspace"><section className="contract-main"><p className="eyebrow">TIMZY CONTRACT</p><h1>{t.title}</h1><p className="contract-intro">{t.intro}</p>{error ? <div className="contract-error" role="alert">{error}</div> : null}
    {phase === 0 ? <div className="contract-step"><h2>{t.market}</h2><div className="contract-grid two"><label className="contract-field"><span>{t.country}</span><input value={selection.registrationCountry} maxLength={2} onChange={(event) => setCountry("registrationCountry", event.target.value)} /></label><label className="contract-field"><span>{t.billingCountry}</span><input value={selection.billingCountry} maxLength={2} onChange={(event) => setCountry("billingCountry", event.target.value)} /></label></div><div className="choice-grid"><button type="button" className={selection.market === "PL" ? "choice-card is-selected" : "choice-card"} onClick={() => changeSelection("market", "PL")}><b>Polska</b><span>7Software sp. z o.o. · PLN</span></button><button type="button" className={selection.market === "INTERNATIONAL" ? "choice-card is-selected" : "choice-card"} onClick={() => changeSelection("market", "INTERNATIONAL")}><b>International</b><span>INNOVARE GROUP LTD · EUR</span></button></div><label className="check-row"><input type="checkbox" checked={marketConfirmed} onChange={(event) => setMarketConfirmed(event.target.checked)} /><span>{t.confirmMarket}<small>{catalog?.market.seller.legalName} · {catalog?.market.currency}</small></span></label></div> : null}
    {phase === 1 ? <div className="contract-step"><h2>{t.language}</h2><div className="choice-grid three">{(["pl","en","es"] as Locale[]).map((language) => <button type="button" key={language} className={locale === language ? "choice-card is-selected" : "choice-card"} onClick={() => changeSelection("language", language)}><b>{language === "pl" ? "Polski" : language === "en" ? "English" : "Español"}</b><span>{catalog?.market.seller.legalName} · {catalog?.market.currency}</span></button>)}</div></div> : null}
    {phase === 2 ? <div className="contract-step"><h2>{t.term}</h2><div className="choice-grid"><button type="button" className={selection.contractTerm === "ANNUAL_12" ? "choice-card is-selected" : "choice-card"} onClick={() => changeSelection("contractTerm", "ANNUAL_12")}><b>{t.annual}</b><span>{t.annualText}</span></button><button type="button" className={selection.contractTerm === "OPEN_ENDED" ? "choice-card is-selected" : "choice-card"} onClick={() => changeSelection("contractTerm", "OPEN_ENDED")}><b>{t.open}</b><span>{t.openText}</span></button></div></div> : null}
    {phase === 3 ? <div className="contract-step"><h2>{t.plan}</h2>{catalog?.plans.length ? <div className="plan-grid">{catalog.plans.map((plan) => <button type="button" key={plan.id} className={selection.planId === plan.id ? "plan-card is-selected" : "plan-card"} onClick={() => changeSelection("planId", plan.id)}>{plan.recommended ? <em>{t.recommended}</em> : null}<h3>{plan.name}</h3><p>{plan.description}</p><strong>{money(plan.prices.find((price) => price.paymentType === "MONTHLY")?.amountMinor, catalog.market.currency, locale)} / {t.perMonth}</strong><ul>{plan.benefits.map((benefit) => <li key={benefit}>✓ {benefit}</li>)}</ul></button>)}</div> : <div className="configuration-blocker"><b>{t.noOffer}</b><code>{catalog?.blockers.join(" · ")}</code></div>}</div> : null}
    {phase === 4 ? <div className="contract-step"><h2>{t.addons}</h2><div className="addon-list">{catalog?.addons.filter((addon) => selection.planId ? addon.compatiblePlanIds.length === 0 || addon.compatiblePlanIds.includes(selection.planId) : addon.standalone).map((addon) => { const chosen = selection.addons.find((item) => item.addonId === addon.id); const included = Boolean(selectedPlan?.includedAddonIds.includes(addon.id)); return <article key={addon.id} className={chosen || included ? "addon-row is-selected" : "addon-row"}><label><input aria-label={addon.name} type="checkbox" checked={Boolean(chosen || included)} disabled={included} onChange={(event) => toggleAddon(addon.id, event.target.checked)} /><span><b>{addon.name}</b><small>{addon.description}</small></span></label><div>{included ? <em>{t.included}</em> : <><strong>{money(addon.prices[0]?.amountMinor, catalog.market.currency, locale)}</strong>{chosen && addon.maxQuantity > 1 ? <input aria-label={t.quantity} type="number" min={addon.minQuantity} max={addon.maxQuantity} value={chosen.quantity} onChange={(event) => setAddonQuantity(addon.id, Number(event.target.value))} /> : null}</>}</div></article>; })}</div></div> : null}
    {phase === 5 ? <form className="contract-step" onSubmit={submitCompany}><h2>{t.company}</h2><div className="contract-grid two"><Field label={t.fields.legalName} name="legalName" value={client.legalName} onChange={setClientField} autoComplete="organization" /><Field label={t.fields.legalForm} name="legalForm" value={client.legalForm} onChange={setClientField} /><Field label={t.fields.registeredAddress} name="registeredAddress" value={client.registeredAddress} onChange={setClientField} autoComplete="street-address" /><Field label={t.fields.postalCode} name="postalCode" value={client.postalCode} onChange={setClientField} autoComplete="postal-code" /><Field label={t.fields.city} name="city" value={client.city} onChange={setClientField} autoComplete="address-level2" /><Field label={t.fields.taxId} name="taxId" value={client.taxId} onChange={setClientField} /><Field label={t.fields.companyNumber} name="companyNumber" value={client.companyNumber ?? ""} onChange={setClientField} required={false} /><Field label={t.fields.representativeName} name="representativeName" value={client.representativeName} onChange={setClientField} autoComplete="name" /><Field label={t.fields.representativePosition} name="representativePosition" value={client.representativePosition} onChange={setClientField} /><Field label={t.fields.businessEmail} name="businessEmail" value={client.businessEmail} onChange={setClientField} type="email" autoComplete="email" /><Field label={t.fields.phone} name="phone" value={client.phone} onChange={setClientField} type="tel" autoComplete="tel" /><Field label={t.fields.brandName} name="brandName" value={client.brandName} onChange={setClientField} /><Field label={t.fields.domain} name="domain" value={client.domain ?? ""} onChange={setClientField} required={false} /><Field label={t.fields.appName} name="appName" value={client.appName} onChange={setClientField} /></div><label className="check-row"><input type="checkbox" checked={client.billingAddressDifferent} onChange={(event) => setClientField("billingAddressDifferent", event.target.checked)} /><span>{t.billingDifferent}</span></label>{client.billingAddressDifferent ? <div className="contract-grid three"><Field label={t.fields.billingAddress} name="billingAddress" value={client.billingAddress ?? ""} onChange={setClientField} /><Field label={t.fields.billingPostalCode} name="billingPostalCode" value={client.billingPostalCode ?? ""} onChange={setClientField} /><Field label={t.fields.billingCity} name="billingCity" value={client.billingCity ?? ""} onChange={setClientField} /></div> : null}<label className="check-row"><input type="checkbox" required checked={client.authorityConfirmed} onChange={(event) => setClientField("authorityConfirmed", event.target.checked)} /><span>{t.accept3}</span></label><button className="button" disabled={busy}>{busy ? "…" : t.save}</button></form> : null}
    {phase === 6 ? <div className="contract-step"><h2>{t.summary}</h2><Summary quote={quote} catalog={catalog} locale={locale} selection={selection} /><div className="summary-lines">{quote?.lines.map((line) => <p key={`${line.itemType}-${line.catalogItemId}-${line.name}`}><span>{line.name} × {line.quantity}{line.included ? ` · ${t.included}` : ""}</span><b>{money(line.totalAmountMinor, quote.currency, locale)}</b></p>)}</div><p className="rollout-note">{t.rollout}</p></div> : null}
    {phase === 7 ? <div className="contract-step"><h2>{t.documents}</h2><div className="document-actions"><a className="button button--light" href="/api/commerce/document-preview?format=html" target="_blank" rel="noreferrer" onClick={() => trackEvent("contract_viewed", { document_format: "html" })}>{t.preview}</a><a className="text-link" href="/api/commerce/document-preview?format=pdf" target="_blank" rel="noreferrer" onClick={() => trackEvent("contract_viewed", { document_format: "pdf" })}>{t.pdf} ↓</a></div><ul className="document-list">{t.documentNames.map((name) => <li key={name}>{name}</li>)}</ul><p className="rollout-note">{t.rollout}</p></div> : null}
    {phase === 8 ? <div className="contract-step"><h2>{t.acceptance}</h2><div className="acceptance-list">{([['agreementAndTerms',t.accept1],['dataProcessing',t.accept2],['authority',t.accept3],...(selection.contractTerm === "ANNUAL_12" ? [['annualCommitment',t.accept4]] : []),['recurringPayment',t.accept5]] as Array<[keyof typeof acceptance,string]>).map(([key,label]) => <label className="check-row" key={key}><input type="checkbox" checked={acceptance[key]} onChange={(event) => setAcceptance((current) => ({ ...current, [key]: event.target.checked }))} /><span>{label}</span></label>)}</div><p className="rollout-note">{t.rollout}</p><button className="button contract-final" disabled={!allAccepted || busy || !quote || !catalog?.checkoutReady} onClick={() => void finish()}>{busy ? "…" : t.final}</button></div> : null}
    <div className="contract-nav">{phase > 0 ? <button type="button" className="text-link" onClick={() => setPhase((current) => current - 1)}>{t.back}</button> : <span />}{phase < 8 && phase !== 5 ? <button type="button" className="button" onClick={next}>{t.next}<span>→</span></button> : null}</div></section><aside className="contract-aside"><Summary quote={quote} catalog={catalog} locale={locale} selection={selection} /></aside></div><details className="mobile-summary"><summary>{t.summary} · {money(quote?.dueTodayNetMinor, quote?.currency ?? catalog?.market.currency ?? "EUR", locale)}</summary><Summary quote={quote} catalog={catalog} locale={locale} selection={selection} /></details></div></main>;
}
