"use client";

import { useEffect, useState } from "react";
import Image from "next/image";

type Summary = { orderNumber: string; language: "pl" | "en" | "es"; companyName: string; registrationNumber: string; signerName: string; position: string; authorityBasis: string; contractTerm: string; documentHash: string; expiresAt: string };

const copy = {
  pl: { title: "Akceptacja drugiego reprezentanta", intro: "Reprezentacja łączna wymaga osobnej akceptacji tej samej wersji dokumentów.", company: "Firma", signer: "Osoba podpisująca", documents: "Dokumenty", read: "Przeczytaj dokumenty", pdf: "Pobierz PDF", code: "Kod jednorazowy z wiadomości e-mail", submit: "Potwierdzam i akceptuję umowę", success: "Akceptacja została zapisana. Osoba rozpoczynająca zamówienie może kontynuować proces.", invalid: "Link jest nieprawidłowy, wygasł albo został już wykorzystany.", statements: ["Potwierdzam, że podane dane firmy są prawidłowe.", "Potwierdzam, że jestem uprawniony do zawarcia umowy w imieniu wskazanej firmy.", "Przeczytałem i akceptuję Umowę oraz Regulamin.", "Akceptuję umowę powierzenia przetwarzania danych.", "Akceptuję zasady cyklicznych płatności.", "Potwierdzam minimalny 12-miesięczny okres obowiązywania umowy oraz obowiązek miesięcznych płatności."] },
  en: { title: "Second representative acceptance", intro: "Joint representation requires a separate acceptance of the same document version.", company: "Company", signer: "Signer", documents: "Documents", read: "Read documents", pdf: "Download PDF", code: "One-time code from the email", submit: "Confirm and accept the agreement", success: "Your acceptance has been recorded. The person who started the order can continue.", invalid: "This link is invalid, expired or has already been used.", statements: ["I confirm that the company details are correct.", "I confirm that I am authorised to enter into the agreement for the stated company.", "I have read and accept the Agreement and Terms.", "I accept the Data Processing Agreement.", "I accept the recurring payment terms.", "I confirm the minimum 12-month term and the obligation to make monthly payments."] },
  es: { title: "Aceptación del segundo representante", intro: "La representación conjunta requiere una aceptación independiente de la misma versión de los documentos.", company: "Empresa", signer: "Firmante", documents: "Documentos", read: "Leer documentos", pdf: "Descargar PDF", code: "Código de un solo uso del correo", submit: "Confirmar y aceptar el contrato", success: "La aceptación se ha registrado. La persona que inició el pedido puede continuar.", invalid: "Este enlace no es válido, ha caducado o ya se ha utilizado.", statements: ["Confirmo que los datos de la empresa son correctos.", "Confirmo que estoy autorizado para celebrar el contrato en nombre de la empresa indicada.", "He leído y acepto el Contrato y las Condiciones.", "Acepto el acuerdo de tratamiento de datos.", "Acepto las condiciones de pagos recurrentes.", "Confirmo el plazo mínimo de 12 meses y la obligación de realizar pagos mensuales."] },
};

export function SecondSignerFlow() {
  const [token, setToken] = useState(""); const [summary, setSummary] = useState<Summary | null>(null); const [error, setError] = useState(""); const [done, setDone] = useState(false); const [busy, setBusy] = useState(false); const [code, setCode] = useState("");
  const [checks, setChecks] = useState([false, false, false, false, false, false]); const locale = summary?.language ?? "en"; const t = copy[locale];
  useEffect(() => { const value = new URLSearchParams(window.location.search).get("token") ?? ""; void fetch(`/api/company-verification/second-signer?token=${encodeURIComponent(value)}`, { credentials: "same-origin" }).then(async (response) => { const payload = await response.json() as { ok: boolean; summary?: Summary; message?: string }; if (!response.ok || !payload.ok || !payload.summary) throw new Error(payload.message || "Invalid link"); setToken(value); setSummary(payload.summary); }).catch(() => setError("INVALID")); }, []);
  if (done) return <main className="co-signer-page"><section className="co-signer-card"><Image src="/assets/timzy-logo-official-purple.png" width="153" height="79" alt="Timzy" /><h1>{t.success}</h1></section></main>;
  if (error === "INVALID") return <main className="co-signer-page"><section className="co-signer-card"><Image src="/assets/timzy-logo-official-purple.png" width="153" height="79" alt="Timzy" /><h1>{t.invalid}</h1></section></main>;
  if (!summary) return <main className="co-signer-page"><section className="co-signer-card">…</section></main>;
  const statementCount = summary.contractTerm === "ANNUAL_12" ? 6 : 5; const allAccepted = checks.slice(0, statementCount).every(Boolean);
  async function accept() { setBusy(true); setError(""); try { const response = await fetch("/api/company-verification/second-signer/accept", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ token, code, companyData: checks[0], authority: checks[1], agreementAndTerms: checks[2], dataProcessing: checks[3], recurringPayment: checks[4], annualCommitment: checks[5], timezone: Intl.DateTimeFormat().resolvedOptions().timeZone }) }); const payload = await response.json() as { ok: boolean; message?: string }; if (!response.ok || !payload.ok) throw new Error(payload.message || "Acceptance failed"); setDone(true); } catch (failure) { setError(failure instanceof Error ? failure.message : "Acceptance failed"); } finally { setBusy(false); } }
  return <main className="co-signer-page" lang={locale}><section className="co-signer-card"><Image src="/assets/timzy-logo-official-purple.png" width="153" height="79" alt="Timzy" /><p className="eyebrow">TIMZY · {summary.orderNumber}</p><h1>{t.title}</h1><p>{t.intro}</p><dl><div><dt>{t.company}</dt><dd>{summary.companyName}<small>{summary.registrationNumber}</small></dd></div><div><dt>{t.signer}</dt><dd>{summary.signerName}<small>{summary.position} · {summary.authorityBasis}</small></dd></div></dl><h2>{t.documents}</h2><div className="document-actions"><a className="button button--light" href={`/api/company-verification/second-signer/document?token=${encodeURIComponent(token)}`} target="_blank" rel="noreferrer">{t.read}</a><a className="text-link" href={`/api/company-verification/second-signer/document?format=pdf&token=${encodeURIComponent(token)}`}>{t.pdf} ↓</a></div><div className="acceptance-list">{t.statements.slice(0, statementCount).map((statement, index) => <label className="check-row" key={statement}><input type="checkbox" checked={checks[index]} onChange={(event) => setChecks((current) => current.map((value, itemIndex) => itemIndex === index ? event.target.checked : value))} /><span>{statement}</span></label>)}</div><label className="contract-field"><span>{t.code}</span><input inputMode="numeric" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} /></label>{error ? <div className="contract-error">{error}</div> : null}<button className="button contract-final" disabled={busy || !allAccepted || code.length !== 6} onClick={() => void accept()}>{busy ? "…" : t.submit}</button></section></main>;
}
