import type { Metadata } from "next";
import { ContactSection } from "./ContactSection";
import { JsonLd } from "./SeoJsonLd";
import type { SiteLocale } from "./IndustryLandingPage";

export type SalesPageKind = "features" | "pricing" | "demo" | "knowledge" | "beauty";

const routes: Record<SiteLocale, Record<SalesPageKind, string>> = {
  en: { features: "/features/", pricing: "/pricing/", demo: "/demo/", knowledge: "/insights/", beauty: "/beauty-spa/" },
  pl: { features: "/pl/funkcje/", pricing: "/pl/cennik/", demo: "/pl/demo/", knowledge: "/pl/baza-wiedzy/", beauty: "/pl/beauty-spa/" },
  es: { features: "/es/funciones/", pricing: "/es/precios/", demo: "/es/demo/", knowledge: "/es/recursos/", beauty: "/es/beauty-spa/" },
};

const content = {
  en: {
    features: { eyebrow: "TIMZY FEATURES", title: "A booking system that keeps the whole customer journey under your brand.", intro: "Timzy combines online bookings, team calendars, payments, client history, loyalty, sales and communication in one configurable product.", cards: [["Online bookings 24/7", "Clients choose a service, specialist and available time without waiting for a reply."], ["Team, resources and locations", "Working hours, absences, roles and bookable resources stay organised."], ["Deposits and payments", "Collect a full payment or a deposit when this module is enabled. Timzy adds no booking commission; payment-provider fees still apply."], ["Retention tools", "Push notifications, vouchers, booking history and free-slot alerts give clients practical reasons to return."], ["Your own app and website", "Use your name, icon, colours, content and selected modules across the customer experience."], ["Custom development", "When your workflow needs more, we can scope dedicated modules, integrations and automations separately."]] },
    pricing: { eyebrow: "TIMZY PRICING", title: "A clear scope first. A price that reflects what your business actually needs.", intro: "Timzy is configured around your brand, modules, team and launch requirements. We do not publish a misleading one-size-fits-all price before understanding that scope.", cards: [["Up to 3 employees", "The standard offer can include up to three employees without an additional employee surcharge."], ["Selected modules", "Bookings, payments, shop, vouchers, memberships and other modules depend on the chosen package."], ["Brand and launch scope", "A ready visual template is faster; individual design, website work and store publication are scoped separately."], ["No Timzy booking commission", "Timzy does not take a percentage of bookings or booking payments. Stripe or another provider may charge processing fees."], ["Custom work priced separately", "Integrations and dedicated functions receive a feasibility review and a separate estimate."], ["Next step", "A free presentation gives us enough context to propose the right scope instead of selling unnecessary modules."]] },
    demo: { eyebrow: "FREE TIMZY DEMO", title: "See the booking journey your clients could use under your brand.", intro: "Tell us your industry, team size and current booking process. We will focus the presentation on the modules and customer journey relevant to your business.", cards: [["Your industry", "Beauty, sport, golf, tennis, automotive or another appointment-based service."], ["Your customer journey", "We show how a client finds a service, selects a time, pays and returns."], ["Your operations", "See calendars, staff or resources, client history and the relevant administration flow."], ["Your brand", "Discuss a ready template or a custom visual direction with your own name, logo and colours."], ["Your questions", "We will separate standard capabilities from optional or custom work."], ["A practical next step", "After the call you will know whether Timzy fits and what should happen next."]] },
    knowledge: { eyebrow: "TIMZY INSIGHTS", title: "Practical guides to bookings, retention and branded customer experience.", intro: "We are preparing evidence-based content for service businesses evaluating booking software. No invented statistics and no copied industry advice.", cards: [["Marketplace or your own app?", "How each model changes brand visibility, customer ownership and acquisition."], ["Timzy or Booksy", "An honest comparison of a separate branded app and a marketplace booking platform."], ["Reducing empty slots", "How reminders, deposits and free-slot alerts address different causes of calendar gaps."], ["Booking software for salons", "A checklist covering team calendars, deposits, client history and repeat visits."], ["Booking systems for sport", "Courts, coaches, recurring training, memberships and group sessions."], ["Booking for detailing", "Packages, vehicle information, service duration, bays and repeat-care reminders."]] },
    beauty: { eyebrow: "TIMZY BEAUTY & SPA", title: "A booking app for salons and SPA businesses that want clients to return to their brand.", intro: "Give clients a direct way to book treatments, choose a specialist, pay a deposit and return through your own branded mobile app.", cards: [["Bookings outside opening hours", "Clients see services, duration and availability without waiting for a message."], ["Favourite specialist and team calendars", "Organise working hours, absences and service assignment in one schedule."], ["Deposits and fewer late gaps", "Take full or partial payment when enabled and use reminders to reinforce the appointment."], ["Free-slot alert", "Clients select days that suit them and can receive a push notification when a matching slot becomes free."], ["Client history and visit notes", "Keep the information needed for better follow-up and the next visit in the configured client environment."], ["Your brand, not a competitor catalogue", "The client sees your services, content, vouchers and shop, without competing salons beside your offer."]] },
  },
  pl: {
    features: { eyebrow: "FUNKCJE TIMZY", title: "Program do rezerwacji wizyt i własna aplikacja pod Twoją marką.", intro: "Timzy łączy rezerwacje online, grafiki zespołu, płatności, historię klienta, lojalność, sprzedaż i komunikację w jednym konfigurowalnym produkcie.", cards: [["Rezerwacje online 24/7", "Klient wybiera usługę, specjalistę i dostępny termin bez oczekiwania na odpowiedź."], ["Zespół, zasoby i lokalizacje", "Godziny pracy, urlopy, role i rezerwowane zasoby pozostają uporządkowane."], ["Zaliczki i płatności", "Po włączeniu modułu pobierasz całość lub część kwoty. Timzy nie dolicza prowizji, ale operator płatności może pobierać swoje opłaty."], ["Narzędzia do powrotów", "Push, vouchery, historia rezerwacji i alert wolnego terminu tworzą praktyczne powody do kolejnej wizyty."], ["Własna aplikacja i strona WWW", "Twoja nazwa, ikona, kolory, treści i wybrane moduły w całej ścieżce klienta."], ["Funkcje dedykowane", "Dodatkowe moduły, integracje i automatyzacje wyceniamy osobno po analizie."]] },
    pricing: { eyebrow: "CENNIK TIMZY", title: "Najpierw jasny zakres. Potem cena odpowiadająca realnym potrzebom firmy.", intro: "Timzy konfigurujemy pod markę, moduły, zespół i wymagania wdrożenia. Jedna cena bez poznania zakresu byłaby pozornie prosta, ale biznesowo myląca.", cards: [["Do 3 pracowników", "Standardowa oferta może obejmować do trzech pracowników bez dopłaty za dodatkowego użytkownika."], ["Wybrane moduły", "Rezerwacje, płatności, sklep, vouchery, karnety i inne elementy zależą od wybranego wariantu."], ["Branding i publikacja", "Gotowy szablon skraca konfigurację. Projekt indywidualny, strona WWW i publikacja są ustalane w zakresie."], ["Bez prowizji Timzy", "Timzy nie pobiera procentu od rezerwacji ani płatności. Stripe może naliczać standardowe opłaty operatora."], ["Rozwój dedykowany", "Integracje i funkcje specjalne otrzymują analizę wykonalności oraz oddzielną wycenę."], ["Bezpłatna prezentacja", "Po rozmowie otrzymasz propozycję zakresu bez wciskania modułów, których nie potrzebujesz."]] },
    demo: { eyebrow: "BEZPŁATNA PREZENTACJA TIMZY", title: "Zobacz proces rezerwacji, z którego klienci mogą korzystać pod Twoją marką.", intro: "Podaj branżę, wielkość zespołu i obecny sposób obsługi rezerwacji. Prezentację skupimy na modułach i ścieżce istotnej dla Twojej firmy.", cards: [["Twoja branża", "Beauty, sport, golf, tenis, automotive albo inna usługa oparta na czasie."], ["Ścieżka klienta", "Zobacz wybór usługi, terminu, płatność i drogę do kolejnej wizyty."], ["Praca zespołu", "Pokażemy grafiki, pracowników lub zasoby, historię klienta i panel administracyjny."], ["Twoja marka", "Porozmawiamy o gotowym szablonie albo indywidualnym projekcie z Twoim logo i kolorami."], ["Jasne odpowiedzi", "Oddzielimy funkcje standardowe od opcjonalnych i dedykowanych."], ["Konkretny kolejny krok", "Po rozmowie będziesz wiedzieć, czy Timzy pasuje i jaki zakres ma sens."]] },
    knowledge: { eyebrow: "BAZA WIEDZY TIMZY", title: "Praktycznie o rezerwacjach, powrotach klientów i budowaniu własnej marki.", intro: "Przygotowujemy treści dla firm porównujących systemy rezerwacji. Bez fikcyjnych statystyk i bez przypadkowych porad kopiowanych między branżami.", cards: [["Marketplace czy własna aplikacja?", "Jak oba modele wpływają na widoczność marki, relację z klientem i pozyskiwanie rezerwacji."], ["Timzy czy Booksy", "Uczciwe porównanie osobnej aplikacji firmowej i platformy marketplace."], ["Jak ograniczać puste terminy", "Przypomnienia, zaliczki i alerty wolnych terminów odpowiadają na różne przyczyny luk w grafiku."], ["Program dla salonu beauty", "Lista funkcji: grafiki, zaliczki, historia klienta i ponowne wizyty."], ["System rezerwacji dla sportu", "Korty, trenerzy, cykliczne treningi, karnety i zajęcia grupowe."], ["Rezerwacje dla detailingu", "Pakiety, dane pojazdu, czas usługi, stanowiska i przypomnienia o kolejnej pielęgnacji."]] },
    beauty: { eyebrow: "TIMZY BEAUTY & SPA", title: "Aplikacja do rezerwacji dla salonu i SPA, która prowadzi klienta z powrotem do Twojej marki.", intro: "Daj klientom bezpośrednią możliwość wyboru zabiegu, specjalisty, terminu i zaliczki we własnej aplikacji mobilnej Twojej firmy.", cards: [["Rezerwacje poza godzinami pracy", "Klient widzi usługi, czas trwania i wolne terminy bez pisania wiadomości."], ["Ulubiony specjalista i grafiki", "Uporządkuj godziny pracy, nieobecności oraz przypisanie usług do zespołu."], ["Zaliczki i mniej późnych luk", "Po włączeniu modułu pobieraj całość lub część kwoty i wzmacniaj rezerwację przypomnieniami."], ["Alert wolnego terminu", "Klient wybiera dogodne dni i może otrzymać push, gdy pasujący termin się zwolni."], ["Historia i notatki po wizycie", "Informacje potrzebne do lepszej obsługi kolejnej wizyty pozostają w środowisku klienta."], ["Twoja marka bez katalogu konkurencji", "Klient widzi Twoje usługi, treści, vouchery i sklep, bez innych salonów obok oferty."]] },
  },
  es: {
    features: { eyebrow: "FUNCIONES TIMZY", title: "Sistema de reservas online y app propia con la marca de tu negocio.", intro: "Timzy reúne reservas online, agendas, pagos, historial, fidelización, ventas y comunicación en un producto configurable.", cards: [["Reservas online 24/7", "El cliente elige servicio, especialista y hora sin esperar respuesta."], ["Equipo, recursos y centros", "Horarios, ausencias, roles y recursos reservables bien organizados."], ["Depósitos y pagos", "Cobra todo o parte cuando el módulo está activo. Timzy no añade comisión; el proveedor de pago puede aplicar sus tarifas."], ["Herramientas de retorno", "Push, vales, historial y alertas de huecos libres dan motivos prácticos para volver."], ["Tu app y tu web", "Tu nombre, icono, colores, contenido y módulos en todo el recorrido."], ["Desarrollo a medida", "Módulos, integraciones y automatizaciones especiales se analizan y presupuestan aparte."]] },
    pricing: { eyebrow: "PRECIOS TIMZY", title: "Primero un alcance claro. Después, un precio que encaje con lo que necesitas.", intro: "Timzy se configura según marca, módulos, equipo y lanzamiento. Un precio único antes de entender el alcance sería engañoso.", cards: [["Hasta 3 empleados", "La oferta estándar puede incluir tres empleados sin recargo adicional por usuario."], ["Módulos elegidos", "Reservas, pagos, tienda, vales y membresías dependen de la variante."], ["Marca y lanzamiento", "Una plantilla acelera la configuración; diseño, web y publicación se definen en el alcance."], ["Sin comisión Timzy", "Timzy no cobra porcentaje de reservas o pagos. Stripe puede aplicar tarifas de procesamiento."], ["Trabajo a medida", "Las integraciones y funciones especiales reciben análisis y presupuesto aparte."], ["Siguiente paso", "Una demo gratuita permite proponer lo adecuado sin vender módulos innecesarios."]] },
    demo: { eyebrow: "DEMO GRATUITA", title: "Descubre el proceso de reserva que tus clientes pueden usar con tu marca.", intro: "Indica sector, tamaño del equipo y proceso actual. Enfocaremos la presentación en los módulos relevantes.", cards: [["Tu sector", "Belleza, deporte, golf, tenis, automotive u otro servicio con citas."], ["Recorrido del cliente", "Servicio, hora, pago y camino hacia la siguiente visita."], ["Operativa", "Agendas, empleados o recursos, historial y administración."], ["Tu marca", "Plantilla preparada o diseño individual con tu logo y colores."], ["Respuestas claras", "Separamos funciones estándar, opcionales y a medida."], ["Un siguiente paso útil", "Sabrás si Timzy encaja y qué alcance tiene sentido."]] },
    knowledge: { eyebrow: "RECURSOS TIMZY", title: "Guías prácticas sobre reservas, fidelización y experiencia de marca.", intro: "Contenido para negocios que comparan sistemas de reservas, sin estadísticas inventadas ni consejos genéricos.", cards: [["Marketplace o app propia", "Cómo cambian la marca, la relación con el cliente y la adquisición."], ["Timzy frente a plataformas", "Comparación honesta entre app independiente y marketplace."], ["Reducir huecos vacíos", "Recordatorios, depósitos y alertas solucionan causas distintas."], ["Software para centros de estética", "Agendas, depósitos, historial y visitas repetidas."], ["Reservas para deporte", "Pistas, entrenadores, sesiones recurrentes y membresías."], ["Reservas para detailing", "Packs, vehículos, duración, puestos y recordatorios."]] },
    beauty: { eyebrow: "TIMZY BEAUTY & SPA", title: "Una app de reservas para centros de estética y SPA que mantiene al cliente cerca de tu marca.", intro: "Permite elegir tratamiento, profesional, hora y depósito desde una app móvil propia de tu negocio.", cards: [["Reservas fuera del horario", "Servicios, duración y disponibilidad sin esperar un mensaje."], ["Profesional favorito y agendas", "Horarios, ausencias y servicios asignados al equipo."], ["Depósitos y menos huecos", "Cobra todo o parte cuando se active y refuerza la cita con recordatorios."], ["Alerta de hueco libre", "El cliente elige días y puede recibir un push cuando aparece una hora adecuada."], ["Historial y notas", "La información útil para la próxima visita queda en el entorno configurado."], ["Tu marca sin competidores", "Servicios, contenido, vales y tienda sin otros centros junto a tu oferta."]] },
  },
} as const;

export function salesMetadata(locale: SiteLocale, kind: SalesPageKind): Metadata {
  const page = content[locale][kind];
  return { title: page.title, description: page.intro, alternates: { canonical: routes[locale][kind], languages: { "en-GB": routes.en[kind], "pl-PL": routes.pl[kind], "es-ES": routes.es[kind], "x-default": routes.en[kind] } }, openGraph: { title: `${page.title} | Timzy`, description: page.intro, url: routes[locale][kind] } };
}

export function SeoSalesPage({ locale, kind }: { locale: SiteLocale; kind: SalesPageKind }) {
  const page = content[locale][kind];
  const root = locale === "en" ? "/" : `/${locale}/`;
  const cta = locale === "pl" ? "Umów bezpłatną prezentację" : locale === "es" ? "Reservar una demo gratuita" : "Book a free demo";
  const contract = { en: ["/contract/", "Configure Timzy"], pl: ["/pl/umowa/", "Skonfiguruj Timzy"], es: ["/es/contrato/", "Configurar Timzy"] }[locale];
  return <main className="seo-sales-page" lang={locale === "en" ? "en-GB" : locale}><JsonLd data={{ "@context": "https://schema.org", "@type": kind === "beauty" ? "WebApplication" : "WebPage", name: page.title, description: page.intro, url: `https://timzy.app${routes[locale][kind]}`, inLanguage: locale }} /><header className="legal-header"><a href={root}><img src="/assets/timzy-logo-official-purple.png" width="307" height="158" alt="Timzy" /></a><a href={root}>← Timzy</a></header><section className="seo-sales-hero"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p><div className="hero-actions"><a className="button" href="#kontakt">{cta}<span>→</span></a>{kind === "pricing" ? <a className="text-link" href={contract[0]}>{contract[1]}<span>↗</span></a> : null}</div></section><section className="seo-sales-grid">{page.cards.map(([title, body], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{body}</p></article>)}</section><ContactSection locale={locale} initialIndustry={kind === "beauty" ? "spa-beauty" : ""} /></main>;
}
